### ISSUE TITLE
Global Colors for Core / Frontera CMS & Portal

### ISSUE THREAD

**Issue by wesleyboar** [TACC/Core-CMS#100]
# Goal

- Review and Standardize Frontera CMS colors.
- Compare with Frontera Portal colors.

# Direction

For Core & Frontera CMS, assume Core colors match Frontera. Clone the stylesheet, and maintain structure if colors change.

For Frontera Portal, mimic variables and structure; review matching values.

**Comment by tacc-wbomar** [comment]
it would be a **long** time before this information could even be used, because Shared Styles are only just becoming possible to even _think_ about.
