### ISSUE TITLE
Navigation Styles via UI Component

### ISSUE THREAD

**Issue by wesleyboar** [TACC/Core-CMS#12]
In GitLab by @tacc-wbomar on Jan 24, 2020, 18:33

# Blockers

- [FP-363](https://jira.tacc.utexas.edu/browse/FP-363) a.k.a. #15
- [FP-531](https://jira.tacc.utexas.edu/browse/FP-531)
- [FP-364](https://jira.tacc.utexas.edu/browse/FP-364)

# Goal

Create a "Navigation" UI Component that can be customized downstream.

# Background

Bootstrap classes are used on the navigation, but they make necessary an ugly set of overrides to do even simple UI changes to the navigation. Instead of fighting Bootstrap on each website, we'll build a minimal internal component to extend instead of override.

# Requirements

1. All Bootstrap navigation UI classes _for the primary header navigation list_ **must** be removed.
1. A new navigation UI component **must** be created.
1. The new component **must**:
    1. Define core structure for primary header navigation.
    1. Define sample website skin for primary header navigation.
    1. Follow [CSS Style Guide](https://confluence.tacc.utexas.edu/display/UP/UI+-+CSS+Style+Guide) and [CSS Organization](https://confluence.tacc.utexas.edu/display/UP/UI+-+CSS+Organization+-+for+UI+Engineers).
1. The new component **must not** style the entire navigation bar.*

\* The component is only for navigation link list, not header layout.

# Direction

Evaluate pros and cons—given bandwidth—of doing a _generic_ "navigation" component or a _specific_ "header primary navigation" component.

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on Feb 3, 2020, 15:13

The decision to clone navigation template on a corresponding Portal will force developer to copy any navigation changes from the CMS to the Portal. This task, if performed, must be done in a way to limit that overhead.

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on May 6, 2020, 17:05

changed title from **Create a "Navigation" UI Component** to **{+BLOCKED: +}Create a "Navigation" UI Component**

**Comment by wesleyboar** [comment]
This ticket is very out-of-date and large in scope. It can ideally be done piecemeal or as part of [CMD-124](https://tacc-main.atlassian.net/browse/CMD-124).
