### ISSUE TITLE
Use New Templates, 2020 Articles

### ISSUE THREAD

**Issue by wesleyboar** [TACC/Core-CMS#138]
# Status

<details>

- [x] https://texascale.org/2020/feature-stories/urgent-computing
- [ ] …

</details>

# Goal

Update Texascale 2020 articles to use appropriate "Article …" templates.

# Requirements

1. Unless no other template is suitable, 2020 Texascale articles **must not** use "Article (Free-Form)" template.

# Background

In 2020, after website was complete, new templates were created for all non-unique 2020 article layouts. But the 2020 articles were not updated to use the new templates, to ensure that launch had zero hiccups.

**Comment by tacc-wbomar** [comment]
Abandoned. The sole CMS Editor is familiar enough with Django CMS that she does not want the limits of a template. Thus, propagating templates serves no purpose.
