### ISSUE TITLE
Use New Templates, 2019 Articles

### ISSUE THREAD

**Issue by wesleyboar** [TACC/Core-CMS#139]
# Goal

Update Texascale 2019 articles to use appropriate "Article …" templates.

# Requirements

1. Unless no other template is suitable, 2020 Texascale articles **must not** use "Article (Free-Form)" template.

# Background

In 2020, after website was complete, new templates were created for all non-unique 2020 article layouts. The 2020 articles would be updated (via #138), but 2019 articles could probably use the same templates.

**Comment by tacc-wbomar** [comment]
Abandoned. The sole CMS Editor is familiar enough with Django CMS that she does not want the limits of a template. Thus, propagating templates serves no purpose.
