### ISSUE TITLE
How to Create Vis/Analytics "Portal"

### ISSUE THREAD

**Issue by wesleyboar** [TACC/Core-CMS#207]
# Alternative

- Let Vis team develop this independent of Core ([private discussion](https://tacc-team.slack.com/archives/C026KLENHA6/p1626879660016000)).

# Goal

## Short-Term

Host as CMS Page with:
- Home page
- Help page
- Jobs “app” page (like [ProTX map](https://pprd.protx.tacc.utexas.edu/protx/))

## Long-Term

It is unclear whether to integrate with Portal (as a Portal, or widget that uses Portal code).

# Direction

## Timeline

If this is needed before new TUP, this could be on its own CMS instance.*

## Servers

The http://vis.tacc.utexas.edu/ has two dev sites. One of which may be available for testing a CMS.
- http://visdev01.tacc.utexas.edu/
- http://visdev02.tacc.utexas.edu/

**Comment by tacc-wbomar** [comment]
Vis team is implementing this independent of Core ([private discussion](https://tacc-team.slack.com/archives/C026KLENHA6/p1626879660016000)).
