### ISSUE TITLE
Docker Scripting for SAD CMS Containerized Workflow

### ISSUE THREAD

**Issue by wesleyboar** [TACC/Core-CMS#23]
# Status

Uncertain. Ask @taoteg.

---

In GitLab by @taoteg on Mar 26, 2020, 17:42
Updated by @tacc-wbomar on Jun 17, 2021, 13:45

# Goal

- Mirror the frontera codebase docker workflow for the cms templated component.
- Adapt deployment to use the container based workflow.

# Direction

Will present an opportunity for divergence from current architecture if we desire:
1. Retain the localized database running outside the container (currently how these sites are deployed).
2. Run the database on an external VM (this approach aligns with the architecture used by the wma portal sites, we could potentially use
    - a) the same db as portal sites or
    - b) stand up a dedicated CMS Database VM that gets its own backup schedule).

I would recommend moving to options 2 & b.
Discuss.

# Reference

- **Option 2A** is _available_ in 2021 (recent use: #240).
- **Option 2B** is still _desirable_ (for [Texascale](https://texascale.org), [Core CMS (SAD)](https://dev.cepcms.tacc.utexas.edu)).

**Comment by tacc-wbomar** [comment]
**Option 2A** is _available_ in 2021 (recent use: #240).

**Option 2B** is still _desirable_ (for [Texascale](https://texascale.org), [Core CMS (SAD)](https://dev.cepcms.tacc.utexas.edu)).

**Comment by wesleyboar** [comment]
This is either completed via [WI-6](https://jira.tacc.utexas.edu/browse/WI-6) in JIRA, or by something that led up to that ticket.
