### ISSUE TITLE
(Finish) Setup of New TACC CMS

### ISSUE THREAD

**Issue by tacc-wbomar** [TACC/Core-CMS#240]
# Goal

Finish set up of new TACC CMS. _This project is *not* supposed to have a Portal (yet)._

> This ticket came from [FP-1075](https://jira.tacc.utexas.edu/browse/FP-1075).

# Requirements
1. A stand-alone CMS is available on http://dev.tup.tacc.utexas.edu/.
1. The new TACC CMS is able to be updated through the latest stable Core deploy process.
1. CMD users H.P. (from CMD) and @tacc-wbomar have administrator access to the CMS.
1. (Preferably) The setup is performed by a "Camino-like" deploy process.

# Background
1. CMD is redesigning TACC in the expectation of using Core CMS.
1. @tacc-wbomar requested creation of a TACC CMS server via RT ticket.
1. Server `dev.tup.tacc.utexas.edu` was created.
1. @tacc-wbomar configured:
    - [Core_CMS](https://jenkins01.tacc.utexas.edu/job/Core_CMS/) Jenkins task
    - [Core_Portal_Deploy](https://jenkins01.tacc.utexas.edu/job/Core_Portal_Deploy/) Jenkins task
    - [Core-Portal-Deployments](https://github.com/TACC/Core-Portal-Deployments) repo
    - [Core-CMS-Resources](https://github.com/TACC/Core-CMS-Resources) repo
1. @tacc-wbomar began steps from [CEPv2 Portal Deployment Checklist ~ Step 20](https://confluence.tacc.utexas.edu/x/LRIFDg).
1. @tacc-wbomar paused work by request of WMA, so WMA could ensure the process is standardized.

# Direction

@tacc-wbomar has already followed *some* of [CEPv2 Portal Deployment Checklist ~ Step 20](https://confluence.tacc.utexas.edu/x/LRIFDg):
- Created `/etc/ssl/dhparam.pem`.
- Created `portal` user (no password).
- Created `.ssh/authorized_keys` and set permissions for it and `.ssh`.
- Did **not** “add key”.
- Did **not** “copy/paste the private key to Stache and/or Jenkins deployment”.

@taoteg asked NSO for SSH access for an automation user (RT #19516).

**Comment by taoteg** [comment]
Task is completed now. As it turns out it was easier to actually deploy the full portal architecture. However, I have not established the storage/execution systems, run indexing, nor imported any apps yet as the portal side is still not under development. Its there waiting when that time comes.

**Comment by taoteg** [comment]
Next up - `dev.cepcms.tacc.utexas.edu` for a truly CMD autonomous CMS test bed.
