### ISSUE TITLE
TACC Learn Portal

### ISSUE THREAD

**Issue by wesleyboar** [TACC/Core-CMS#243]
**Abandoned.** Short-term solution is [TUP-607](https://tacc-main.atlassian.net/browse/TUP-607). And https://learn.tacc.utexas.edu/ redirects to https://tacc.utexas.edu/use-tacc/training/.

# Goal

Allow event creation that performs action upon date.

# Requirements

1. TACC account **must** be required for user to register for event.
    - How do we restrict registration? See [TACC Learn Portal][tacc-learn].
2. User **must** be able to register for an event.
3. User **must** receive notification as event nears.
4. A third-party software **may** be used.
5. If using a third-party software, its events **should** be able to be listed on the TACC site.
6. A CMS plugin **may** be used.
7. Event registration **must** require creation of "training allocation" for user.
7. Creation of "training allocation" **may** be separate from event registration login.

# Direction

See [TACC Learn Portal][tacc-learn].

## Requirement 4 & 6

A third-party software is likely preferable to a CMS plugin, because it likely is better maintained and has more features.

## Requirement 7 & 8

> Registration needs to be tied into TAS (or I guess TRAM) to create the training allocation they will be required to use. That is separate from the login for registration, but rather once registered they have the training allocation on the scheduled dates. This function currently exists, I believe.
>
> — M.S.

## Team Coordination

See https://github.com/TACC/Core-CMS/issues/243#issuecomment-858791530.

[tacc-learn]: https://learn.tacc.utexas.edu/

**Comment by tacc-wbomar** [comment]
# Proposal for Team Coordination

1. **WMA** gives TACC Learn Team a stand-alone CMS based off Core.
1. **TACC Learn team** uses this to create a new TACC Learn CMS.
1. **TACC Learn team** can integrate 3rd-party software into new TACC Learn CMS.
1. **Core CMS team** manage how much of the integration gets into Core.
1. _As necessary_, **CMD** designs and styles new TACC Learn CMS.
1. _Finally_, **CMD** subsumes new TACC Learn CMS into new TACC.

**Comment by wesleyboar** [comment]
**Abandoned.** Short-term solution is [TUP-607](https://tacc-main.atlassian.net/browse/TUP-607).
