### ISSUE TITLE
Fix/Support CMS `align-___` Classes

### ISSUE THREAD

**Issue by wesleyboar** [TACC/Core-CMS#25]
In GitLab by @tacc-wbomar on Apr 3, 2020, 18:48

# Goal

Fix or support the use of alignment configuration for the "Picture / Image" plugin

# Background

The Bootstrap plugin "Picture / Image" (which uses the [DjangoCMS plugin "Picture"](https://github.com/divio/djangocms-picture)) offers an alignment configuration of none, left, center, or right. It is meant to achieve the chosen alignment by setting a class on the plugin's markup. But, the classes do not have associated styles.

The `align-center` class might be in use on Texascale.org; see [Snippet #14](https://texascale.org/admin/djangocms_snippet/snippet/14/change/).

# Direction

Maybe, it is expected that the plugin user define the styles for the classes…

## Research

* The classes are [built-in to the plugin](https://github.com/divio/djangocms-picture/blob/b8ae5f0ccd15744743a2e2106cb252f4266abd70/djangocms_picture/cms_plugins.py#L64).
* The classes are [configurable](https://github.com/divio/djangocms-picture#user-content-configuration) (see `DJANGOCMS_PICTURE_ALIGN`).
* One known bug with the `align-center`/`align-left` classes was fixed via [PR #45, Release 2.0.5](https://github.com/divio/djangocms-picture/pull/45).

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on Apr 3, 2020, 19:27

changed title from **Support CMS `align-___` Classes** to **{+Fix/+}Support CMS `align-___` Classes**

**Comment by wesleyboar** [comment]
This was done on Core for TACC site redesign.
