### ISSUE TITLE
Document How to Use Animated `.gif`s

### ISSUE THREAD

**Issue by wesleyboar** [TACC/Core-CMS#26]
> [!NOTE]
> Moved to [CMD-126](https://tacc-main.atlassian.net/browse/CMD-126).

In GitLab by @tacc-wbomar on Apr 5, 2020, 15:44

# Goal

Document [How to Use (Animated) GIFs](https://texascale.org/testing/how-use-gifs/?edit) for the Core, instead of for Texascale only.

# Requirements

1. Documentation for Core / all Stand-Alone Django sites **must** exist.
1. Documentation **may** be in Clonfluence.
1. Documentation **may** be a Core CMS webpage.

# Direction

Use [How to Use GIFs](https://texascale.org/testing/how-use-gifs/?edit) content.

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on Apr 5, 2020, 15:55

changed title from **Document {-"How to Use .GIFs"-}** to **Document {+How to Use Animated `.gif`s+}**
