### ISSUE TITLE
Support Animated `.gif` by Default

### ISSUE THREAD

**Issue by wesleyboar** [TACC/Core-CMS#27]
> [!NOTE]
> Moved to [CMD-125](https://tacc-main.atlassian.net/browse/CMD-125).

In GitLab by @tacc-wbomar on Apr 5, 2020, 15:55

# Goal

Set default "Cropping Settings", of Picture / Image plugin, for `.gif` images to be configuration that supports animated .`gif`s.

# Requirements

1. The setting "Use original image" **should** be set.\
    _(one way @tacc-wbomar found to render `.gif` animation)_
1. The setting "[typo; value lost]" **should not** be set.\
    _(not allowed in conjunction with "Use original image")_

# Reference

- [Make default cropping options configurable](https://github.com/divio/djangocms-picture/issues/36)
- Screenshot of settings from CMS user's perspective\
    ![Use_these_crop_settings_to_support_a_Gif_image](https://gitlab.tacc.utexas.edu/wma-cms/cms-site-template/uploads/e8f14e7ced565b3f4eb3bf26cd38496e/Use_these_crop_settings_to_support_a_Gif_image.png)

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on Apr 5, 2020, 15:55

changed title from **{-Configure CMS to -}Support Animated `.gif` by Default** to **Support Animated `.gif` by Default**

**Comment by wesleyboar** [comment]
Moved to [CMD-125](https://tacc-main.atlassian.net/browse/CMD-125).
