### ISSUE TITLE
Improve Article Plugin Usability

### ISSUE THREAD

**Issue by wesleyboar** [TACC/Core-CMS#273]
# Goal

Improve Article List & Article Preview plugins.

# Requirements

1. The help text about “See all” __must__ be clear if link is not present.
1. The image ratio and size __must__ be restricted (per plugin if possible).*
    - This will avoid user uploading giant article image (even if it appears small).
1. Title and Abstract __must__ have minimum character count.
1. The Abstract field __must__ be renamed to Description.
1. The Allocations Article Preview __must__:
    - _either_ require a link
    - _or_ render without a link
1. The Bootstrap Image / Picture plugin __should not__ be available.*
    - Because Picture plugin is preferred.

> \* May become its own task.

# Background

Designers performed user test of plugins as of PR https://github.com/TACC/Core-CMS/pull/264.

**Comment by tacc-wbomar** [comment]
Static Article Plugins are removed ([FP-1360](https://jira.tacc.utexas.edu/browse/FP-1360)), so this ticket is moot.
