### ISSUE TITLE
"Link in Text" Plugin

### ISSUE THREAD

**Issue by wesleyboar** [TACC/Core-CMS#306]
# Goal

Create a plugin that allows user to create one line of text with a link in it.

# Requirements

1. Plugin **must** support link within text.
2. Plugin **must not** output a `<p>` tag.
3. Plugin **must not** support new lines.
4. Plugin **must** be supported as child plugin for Label of "Data List Item".
5. Plugin **may** use markdown for input.
6. The link **must** support text, internal URL, external URL, target, and anchor.

# Direction

## ~~CKEditor~~

Do **not** use default "Text" plugin / CKEditor (unless you can remove all extraneous features—which is most features—in a reliable, maintainable way).

## ★ Markdown Plugin

Do consider installing an external, Markdown plugin for Django CMS, but repo must be not too old, well-maintained, and quality code.

## Parse Text Field

A low tech-solution is:
- plugin that extends LinkPlugin
- plugin has a Text field
- render replaces `[link]` in Text field with link

# Background

1. The "Data List Item" plugin (from #75) needs to _also_ support a Label that can have a link within text.
2. Using CKEditor is overkill for feature and overhead to reduce its feature set.
3. Combining Text plugin and Link plugin is not feasible.
4. Parsing Text field value to inject a link from a Link plugin is an okay idea.

**Comment by tacc-wbomar** [comment]
No, because https://github.com/TACC/Core-CMS/issues/75:
- will be replaced with a simpler solution
- was the only reason for this issue
- can be performed without a plugin\*

_\* We have become very strict about what internal plugins we maintain._
