### ISSUE TITLE
Create Non-admin User Permsissions for CMS

### ISSUE THREAD

**Issue by fnets** [TACC/Core-CMS#307]
In order to turn UX on and off for users that log into the CMS, we need to add a set of permissions for non-admin users.

We will need to create user permissions that are secure and invisible so that they don't know that they are logged in.

I haven't been able to find any alternatives, yet.

There is a JIRA, [FP-1148](https://jira.tacc.utexas.edu/browse/FP-1148)

**Comment by tacc-wbomar** [comment]
My edits have been reverted. I have instead created a new issue, GH-317.

**Comment by tacc-wbomar** [comment]
This ticket has been mentioned again in https://github.com/TACC/Core-CMS/issues/317#issuecomment-902257583.

**Comment by tacc-wbomar** [comment]
Closed (with it's related JIRA tickets, FP-1147, FP-1148).
