### ISSUE TITLE
Prevent Unauthenticated Access to Pages Marked by CMS Admin

### ISSUE THREAD

**Issue by tacc-wbomar** [TACC/Core-CMS#317]
# Goal

1. Prevent unauthenticated [website] user from accessing Portal content shown on marked CMS pages.
2. Allow CMS admin user to mark certain CMS pages as requiring authorization.\*

> <details><summary>Foonotes</summary>
> 
> \* Without this goal (or similar solution), developer must maintain a list of pages, or must track a parent page for each project in which such pages live, which requires a deploy for new pages. These pages are created by users, and deploy for every publish of such a page is not feasible at scale (see [question](https://github.com/TACC/Core-CMS/issues/317#issuecomment-902264071) and [alternative](https://github.com/TACC/Core-CMS/issues/317#issuecomment-902732688)).
> 
> </details>

# Requirements

1. Given page is marked as requires authentication,
  And page is loading,
  Then CMS must check whether user is authenticated.
2. Given user is authorized,
  And page is marked as requiring authentication,
  Then Page must load user-facing message explaining access limitation and directing user to login,
  And page must not show protected content.
3. User-facing message must have the following content:
    - link to Portal login page
    - message like "To access the Portal, [log in to the portal](https://example.com)."
4. User may view page if:
    - user is logged into the Portal
      & page is marked as requiring Portal login
    - user is _not_ logged into the Portal
      & page is _not_ marked as requiring Portal login
5. A CMS user must be able to mark page as requiring, or not requiring, authentication.
    - ⚠️ What permissions does a user need to be allowed to do this?

# Direction

1. Extend Django Page model.
2. There are different ways to load this message. Here are some ideas:
    1. <details><summary>(Portal, client-side) Load message or content from Portal.*</summary>

    	1. Use "user is authenticated" state from Portal.
    	2. Use template logic to conditionally provide content or message.

		</details>

		- Does not achieve goal 2.

	2. <details><summary>(CMS, server-side) Include template from template of loaded page.</summary>

		1. Retrieve "user is authenticated" state from Portal endpoint.
		2. Provide "user is authenticated" state to template via template tag.
    	3. Use template logic to conditionally provide content or message.
		4. To provide message, include another template.
		5. Resolve caveats:
		    - Which template should load this template logic? Ideas:
		    	- __`base.html`__
		    	  (this would allow CMS users to choose any template)
		    	- ~~new template just for pages that need portal auth~~
		    	  (this would limit layout flexibility via template choice)

		</details>

		- Has fewest caveats.

	3. <details><summary>(CMS, server-side) Redirect user to "No access" page.</summary>

		1. Retrieve "user is authenticated" state from Portal endpoint.
		2. Provide "user is authenticated" state to `urls.py`.
    	3. Use Python logic to conditionally load page or redirect user to a CMS page.
		4. To redirect user to a CMS page:
		    - Have a CMS page that loads a template.
		    - Have a template provides the message.
		5. Resolve caveats:
			- Create page for every portal that needs this.†
			- Provide the original page context (page name and URL) to the template.

		</details>

		- Has most caveats.
3. (none)
4. The Portal has an API endpoint to determine whether user is logged in to Portal.
5. For a user to mark a page via the interface as accessible (or not), the Page model probably needs a new property and the "Pages" admin interface, a new column of checkboxes.

    <details><summary>Details</summary>

	The Page model needs a new property (like `is_logged_into_portal`), so the interface can display a form field to change that property. The admin form template will need to be extended to add a column with checkboxes.

	</details>

    <details><summary>Concerns</summary>

	How much of the form interface extension is duplicating the original form? Mass template duplication is difficult to maintain across version upgrades.

	</details>

    <details><summary>Past Progress</summary>

	- https://github.com/TACC/Core-Portal/pull/473/

	</details>

> <details><summary>Footnotes</summary>
> 
> \* Post-brainstorm meeting idea from @xandroc based on @tacc-wbomar's summary of issue; but @tacc-wbomar forgot about goal 2. @xandroc is welcome to provide further direction.
> † We do not have a way yet to automatically create a page (GH-146). 
> 
> </details>

# Reference

- [StackOverflow: How to override and extend basic Django admin templates?](https://stackoverflow.com/a/6586068/11817077) ([old blog post](https://heyman.info/2011/jul/5/extending-templates-specific-django-app/))
- [Django: Overriding admin templates](https://docs.djangoproject.com/en/2.2/ref/contrib/admin/#overriding-admin-templates)
- [StackOverflow: How to override Django-CMS templates](https://stackoverflow.com/a/39099777/11817077)
- [Django CMS: How to extend Page & Title models](https://docs.django-cms.org/en/release-3.6.x/how_to/extending_page_title.html)

# Background

1. [FP-1148](https://jira.tacc.utexas.edu/browse/FP-1148)
2. https://github.com/TACC/Core-CMS/issues/307
3. 2021-08-19: Peer brainstorming meeting.

**Comment by xandroc** [comment]
> 2. Given user is authorized,

How would the portal know if a user is authorized if a user isn't logged in?

**Comment by tacc-wbomar** [comment]
> > 1. Given user is authorized,
> 
> How would the portal know if a user is authorized if a user isn't logged in?

I do not know. I understand authorization only so far as:
> 4. User has authorization to view page if:
>     - user is logged into the Portal
>     - page is marked as requiring authorization
>     - ⚠️ (anything else?)

I have pinged the original meeting group to review this ticket and clarify holes, like authorization details.

**Comment by xandroc** [comment]
> Create Non-admin User Permsissions for CMS #307

This shouldn't be necessary, the only status we need is logged in or not logged in

**Comment by xandroc** [comment]
> Without this goal (or similar solution), developer must maintain a list of pages, or must track a parent page for each project in which such pages live, which requires a deploy for new pages. These pages are created by users, and deploy for every publish of such a page is not feasible at scale.

Have we shown that these are created at scale in existing core portal deployments?

**Comment by rstijerina** [comment]
I would replace "authorized" with "authenticated"

**Comment by tacc-wbomar** [comment]
Authorization is now authentication, and related wording has been simplified.

_**Thank you.** I was confused whether there was more to it than just being logged in. Much about users was discussed in the meeting._

---

I second [Alex's question](https://github.com/TACC/Core-CMS/issues/317#issuecomment-902264071). If the use case is primarily A2CPS and a little ProTX right now, and no one else in the immediate future, then let's reconsider goal 2, because:
1. Stakeholder may be willing to wait for deploy for each new such page.
2. Though a deploy for each new such page annoys us, deploys are quick.
3. Without goal 2, we can use the—much simpler and faster—Portal client-side solution.

**Comment by fnets** [comment]
There are new reports being developed right now for A2CPS, which will be new pages. We have to redeploy the site every time we add a new page anyway, because nginx needs to be reconfigured.

**Comment by taoteg** [comment]
Note: We also need to be able to publish pages that do **not** require authentication to view in the CMS.

**Comment by tacc-wbomar** [comment]
Everyone, I've added a fifth "Requirement" (and "Direction" for it) for the change to the CMS admin interface for Pages.

---

@taoteg I have tweaked and added wording to clarify that some pages with Portal content "do **not** require authorization to view in CMS".

**Comment by tacc-wbomar** [comment]
Closed. Resolved via https://github.com/TACC/Core-CMS/pull/341.
