### ISSUE TITLE
Callout Plugin - Require & Integrate Image

### ISSUE THREAD

**Issue by wesleyboar** [TACC/Core-CMS#328]
# Goal

- Require image as part of callout.
- (assumed implementation) Integrate image into plugin (not as child plugin).

# Requirements

1. Image __must__ be a required feature of the Callout plugin.
2. If anything learned benefits GH-327, then notes __must__ be added to there.

# Direction

If we extend the Picture plugin, instead of supporting it as a child plugin, then we can require its fields.

**Comment by tacc-wbomar** [comment]
This issue is now moot, because the callout Plugin should be removed, thus image cannot be required nor integrated.
