### ISSUE TITLE
Split Page Meta and Blog/News into Two Features

### ISSUE THREAD

**Issue by wesleyboar** [TACC/Core-CMS#48]
In GitLab by @tacc-wbomar on Sep 3, 2020, 15:02

# Goal

Separate `djangocms-blog` and `djangocms-page-meta` into separate features.

# Background

1. Approx. 4 months ago, Aaron requested the feature which is available in `djangocms-meta`.
2. Wesley found that `djangocms-blog` and `djangocms-page-meta` both use `djangocms-meta`.
3. Wesley knew that `djangocms-blog`:
    - would be required for new TACC CMS
    - is suitable for Texascale CMS
4. Texascale CMS __needs__ `djangocms-page-meta`.
5. Texascale CMS will __not__ use `djangocms-blog`.[^1]

# Reference

Relevant Social Media:
- Twitter
- Facebook
- Instagram
- LinkedIn

# Direction

There is code in `taccsite_cms/templates/base.html` that may be written differently if both, only one, or the other feature is enabled. No other template should need to be changed. Other files do need to be changed, though.

# Notes

This is assigned to the "No Forks" milestone, because without this change, Texascale would need new one-off template code to ad-hoc support social media metadata (what `djangocms-meta` offers the two aforementioned plugins).

# Footnotes

[^1]: Hedda does not want to change how Texascale pages are built, because 2019 is done and working and 2020 is coming up and needs to be developed quickly—no time to test new tools. I will wait and plan to test the tool on Frontera CMS redesign or new TACC CMS (instead of on Texascale CMS).

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on Sep 3, 2020, 16:52

changed title from **Split Page Meta and Blog/News into {-2-} Features** to **Split Page Meta and Blog/News into {+Two+} Features**

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on Nov 16, 2020, 14:01

removed milestone

**Comment by wesleyboar** [comment]
Seems to have been completed, because `djangocms_page_meta` is installed by default, and blog install requires more settings.
