### ISSUE TITLE
Fix Per-Page Permissions in Django CMS

### ISSUE THREAD

**Issue by wesleyboar** [TACC/Core-CMS#51]
In GitLab by @tacc-wbomar on Oct 20, 2020, 16:11

# Dependencies

- [x] https://github.com/TACC/Core-CMS/issues/23

# Problem

[Page permissions is broken on Django 1.11 and DjangoCMS>=3.6](https://github.com/django-cms/django-cms/issues/6774)

_P.S. Not our fault._

# Symptoms

- [Page permissions form (table) not rendering](https://github.com/django-cms/django-cms/issues/6689)

# Solutions (Approved)

## 3. ✓ Upgrade Django

> This will be more easily performed after #23.

[Upgrade to Django 2.1](https://github.com/django-cms/django-cms/issues/6689#issuecomment-519936597), then test __everything__.

- [x] __~~`cms-site-template`~~ `core-cms` & `example-cms`__
- [x] __`texascale-org`__
- [x] __`frontera-cms`__
- [x] `lccf-tacc`
- [x] `tapis-project-org`
- [x] `sciviscolor-cms`

# Solutions (Declined)

<details><summary>Solutions That Have Been Declined</summary>

### 2. ~~Try to Publish Page, But Limit View Access~~
- [Page permissions form (table) not rendering.](https://github.com/django-cms/django-cms/issues/6689)
- [Page permissions is broken on Django 1.11 and DjangoCMS>=3.6](https://github.com/django-cms/django-cms/issues/6774)

### 1. ~~Try to Allow View-But-Not-Edit Access to Auth'd Users~~
- [StackOverflow user wanting the same thing, but unable to achieve it (exactly)](https://stackoverflow.com/q/60061536)
- [DjangoCMS user, who failed similar goal, describes Django CMS permission pitfalls](https://www.webrunners.de/en/django-cms-permission-pitfalls/)

</details>

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on Dec 2, 2020, 10:24

closed

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on Dec 2, 2020, 10:25

reopened

**Comment by wesleyboar** [comment]
The final sites were migrated over via [WI-6](https://jira.tacc.utexas.edu/browse/WI-6).
