### ISSUE TITLE
Unable to Perform Database Migrations on Master Branch

### ISSUE THREAD

**Issue by wesleyboar** [TACC/Core-CMS#54]
# Status

Uncertain. This ticket might be out of date, or only relevant to Texascale, because:
- We are on `main` branch, not `master` (which ticket refers to).
- @tacc-wbomar thinks Texascale has had successful migrations (for [v3.0.0](https://github.com/TACC/Core-CMS/releases/tag/v3.0.0) plugins) since this ticket.

---

In GitLab by @tacc-wbomar on Nov 16, 2020, 17:01

# Dependencies

- [x] https://github.com/TACC/Core-CMS/issues/23

# Goal

Resolve database migration error on production, which is caused by Postgres-Django version incompatibility.

## Importance

- The `master` branch has changes that will break any non-containerized CMS (i.e. all except Frontera CMS).
- Features from `master` can not be deployed without relying on outdated or fractured branches.

## Notes

- This issue was found after activating the blog feature while being on a `master` commit* that includes Django version update commit (ae1701ffa4849ea9f790a5dac8059a3f1cda8817).
- We may safely test upgrade on [texascale-dev.tacc.utexas.edu](https://texascale-dev.tacc.utexas.edu/), but the issue can affect all [Deployed CMS Sites](https://confluence.tacc.utexas.edu/display/UP/Deployed+CMS+Sites).

> \* One specific commit tested on was ea90c842e105ca4cb96981152ccc0692c120e26c, but others (that occurred after ae1701ffa4849ea9f790a5dac8059a3f1cda8817) were also tested.

# Background

When trying to run `python3 manage.py migrate` (for #35), the error `django.db.utils.ProgrammingError: syntax error at or near "WITH ORDINALITY` occurs. This error is commonly stated to occur because [Django 2.1 dropped support for PostgreSQL 9.3](https://docs.djangoproject.com/en/2.1/releases/2.1/#dropped-support-for-postgresql-9-3). This occurs on `upstream-master-on-master` and `upstream-master-on-master--task/35` on https://texascale-dev.tacc.utexas.edu.

# Direction (Approved)

## Z. → Containerize Production

> This will be done near or during early 2021 via:
> - #23

Desirable but __not__ suggested, because "A. Upgrade Postgres Database" seems easier, and available sooner.

The [containerized instances use Postgres 11.5](https://gitlab.tacc.utexas.edu/wma-cms/cms-site-template/blob/master/docker-compose.yml#L19).

## A. ✓ Upgrade Postgres Database from 9.2 to 9.4+

> This successfully was performed and fixed the problem in:
> - [x] https://texascale-dev.tacc.utexas.edu
> - [x] https://texascale.org

__Suggested__, because it seems easier than "Z. Containerize Production".

- ["Installing Postgresql 11 solved the problem."](https://stackoverflow.com/a/55781529)
- ["try to update your postgres version"](https://stackoverflow.com/a/55740884)
- ["updating my Postgres version fixed this for me"](https://stackoverflow.com/a/51927443)
- ["looks like you have a postgresql that is incompatible with Django 2.1 (ie older than 9.4)"](https://github.com/encode/django-rest-framework/issues/6357#issuecomment-447571824)

### Reference

- [PostgreSQL 9.0.23 Documentation, 15.4 Upgrading](https://www.postgresql.org/docs/9.0/install-upgrading.html)

# Direction (Declined)

<details><summary>Solutions That Have Been Declined</summary>

## B. ~~Downgrade Django Version~~

__Not__ suggested, because we already updated everything, and the outdated Postgres database is the problem.

- ["In my case, downgrading to version 2.0 worked."](https://stackoverflow.com/a/51847764)
- ["The bug is for django version greater than 2.0. Downgrading the django version to 2.0 and Postgres version same as 9.3 worked for me."](https://stackoverflow.com/a/57217702)

## C. ~~"Reset" The Migrations~~

__Not__ suggested, because Wes when tried this during #41 it caused even more trouble.

- ["Whenever you are adding any new field and facing migrate error"](https://stackoverflow.com/a/51914506)
- ["when you get this error, go into your migrations folder and delete [specific things.] Then run `makemigrations` and `migrate` again."](https://stackoverflow.com/a/35368986)

## D. ~~Search Whether Some App Has `CharField` Issue~~

__Not__ suggested, because the outdated Postgres database is the problem.

- ["This can also happen when making a CharField nullable if you do not specify max_length."](https://stackoverflow.com/a/63158784)
- ["I created a new CharField and it migrated just fine. I am running PSQL 9.5.21 and Psycopg 2.8.5 so those aren't the problem."](https://stackoverflow.com/a/61805648)

</details>

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on Nov 16, 2020, 17:32

changed title from **{-Upgrade Postgres Databases-} on Production** to **{+Fix Django/Postgres Version Conflict+} on Production**

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on Nov 16, 2020, 17:43

changed title from **Fix Django/Postgres Version Conflict on {-Production-}** to **Fix Django/Postgres Version Conflict on {+CMS Website Servers+}**

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on Nov 16, 2020, 17:43

changed title from **{-Fix -}Django/Postgres Version Conflict on CMS Website Servers** to **Django/Postgres Version Conflict on CMS Website Servers**

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on Nov 16, 2020, 17:49

changed title from **D{-jango/Postgres Version Conflict on CMS Website Servers-}** to **D{+atabase Migration Error (Pending Specifics)+}**

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on Nov 16, 2020, 17:52

changed title from **{-Database Migration Error (Pending Specifics)-}** to **{+Unable to Perform Database Migrations on Latest Master Branch Commit+}**

**Comment by tacc-wbomar** [comment]
In GitLab by @tacc-wbomar on Nov 24, 2020, 09:31

changed title from **Unable to Perform Database Migrations on {-Recent Master Branch Commit-}** to **Unable to Perform Database Migrations on {+Master Branch+}**

**Comment by wesleyboar** [comment]
This must be done. Database migrations have been possible for a long time. Also, news/blog app is installed separate form Core, now. And the last status in the PR description suggests Texascale, which does not—and has no plans to—use news/blog app (though it is installed).
