### ISSUE TITLE
Figure Plugin

### ISSUE THREAD

**Issue by wesleyboar** [TACC/Core-CMS#72]
# Goal
 * Create [CMS UI - Components - Figure](https://confluence.tacc.utexas.edu/x/FoEjCQ) in Core.
 * Style [CMS UI - Components - Figure](https://confluence.tacc.utexas.edu/x/FoEjCQ) in Frontera.

# Direction

 1. Reference [figure.css](https://github.com/TACC/cms-site-resources/blob/master/texascale-org/static/texascale-org/css/src/_imports/components/bootstrap.figure.css) from Texascale.

**Comment by tacc-wbomar** [comment]
We have decided to not use TACC-maintained plugins unless truly beneficial, like when we have far more website editors than we actually do.
