### ISSUE TITLE
Global Layout / Spacing Styles

### ISSUE THREAD

**Issue by wesleyboar** [TACC/Core-CMS#99]
# Dependencies

- #171

# Goal

Review and/or Standardize horizontal spacing, vertical spacing, and ~~media queries~~ (✓).

## Expectations

1. Horizontal spacing has variables.
2. Vertical spacing has variables.
3. (✓) ~~Define media queries variables.~~

### Technical

- Use environmental variables (`env()`).
- Reference branch `task/GH-99-global-spacing`.

### Design

- small gap(s) for related items
- medium gap(s) for less-related items
- large gap(s) for minimally-related items
- there may be multiple options for each size of gap

# Reference

- [Shared UI - Constants - Units](https://confluence.tacc.utexas.edu/display/~wbomar/Shared+UI+-+Constants+-+Units) (see "Spacing")
- ~~[Bootstrap 4.0 Spacing](https://getbootstrap.com/docs/4.0/utilities/spacing/) (see "Where size is one of:")~~

**Comment by tacc-wbomar** [comment]
This has become a nice to have, because rounding and making consistent the values from Design is not too much overhead and the values have not been challenged by Design.

**Comment by wesleyboar** [comment]
Closing, because:

- Design does not use consistent spacing.
- The current usage of global spacing could use `em` (simpler and suitable and allowed).
- Using `px` requires decimal values, because CMS now is base font 10px, not 16px—decimal pixel values are… odd.[^1]

[^1]: I have not researched how all browsers do or should interpret them, and don't care, because it's weird to atomic units with decimals, like splitting atoms and the global spacing need was false. CMS is being designed without thema nd still looks good (when a complete design is provided). Sacrifices for expediency.
